// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvfpwzlfyvjueabkyjym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12ZnB3emxmeXZqdWVhYmt5anltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTAxODAsImV4cCI6MjA2NTA2NjE4MH0.HV3ycBd6qTHgxQVZ-u9JDgXnXOtY2W2J5HKtPnm7BHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);